### ISSUE TITLE
目前尚未兼容app端

### ISSUE THREAD

**Issue by wyhPro** [LuckDraw/uni-luck-draw#3]
机型：红米10x
系统：安卓10

**`[Vue warn]: Error in event handler for "view.vdSyncCallback": "TypeError: e.getSystemInfoSync is not a function"`**

**Comment by buuing** [comment]
小程序还是app

**Comment by wyhPro** [comment]
> 小程序还是app

app 
 function Lucky(config)``
没得flag参数

**Comment by buuing** [comment]
> app
> function Lucky(config)``
> 没得flag参数

很抱歉, 目前尚未兼容app,

**Comment by wyhPro** [comment]
> > app
> > function Lucky(config)``
> > 没得flag参数
> 
> 很抱歉, 目前尚未兼容app,

haoba QAQ

**Comment by buuing** [comment]
因为都是canvas绘制, 相关api兼容问题一大堆, 我已经预感到兼容app端要话费很久时间了, 所以, 得慢慢来

**Comment by buuing** [comment]
> haoba QAQ

但是欢迎一起来参与兼容各端的开发

**Comment by wyhPro** [comment]
> > haoba QAQ
> 
> 但是欢迎一起来参与兼容各端的开发

我看看

**Comment by buuing** [comment]
> 我看看

核心逻辑在`lucky-canvas`这个包, 基于`ts + rollup`开发, 加油

**Comment by buuing** [comment]
目前app端简单测试通过, 但是定时器十分卡顿
