### ISSUE TITLE
请问怎么分别设置转盘的启动速度和停止速度

### ISSUE THREAD

**Issue by zdwork** [LuckDraw/uni-luck-draw#5]

**Comment by buuing** [comment]
不能, 速度只有一个, 那就是speed峰值速度, 加速是在设定时间内从0加速到峰值, 停止同样也是从峰值到0, 所以峰值是固定的, 不能变化

**Comment by zdwork** [comment]
转盘内容全部设置成图片可以吗

**Comment by buuing** [comment]
> 转盘内容全部设置成图片可以吗

可以的

**Comment by zdwork** [comment]
我的意思是金额也是图片，

**Comment by buuing** [comment]
> 我的意思是金额也是图片，

我的意思是可以

**Comment by zdwork** [comment]
{ title: '1元红包', background: '#f9e3bb', fonts: [{ text: '1元红包', top: '18%' }] },
          { title: '100元红包', background: '#f8d384', fonts: [{ text: '100元红包', top: '18%' }] },
就是写这个了，金额在图片上了

**Comment by buuing** [comment]
那你不加`fonts`不就得了, 只用`imgs`

**Comment by zdwork** [comment]
哦哦 牛

**Comment by buuing** [comment]
仔细看一下文档, 上面的`fonts`和`imgs`参数都是`?:`在ts里面表示可传参数

**Comment by zdwork** [comment]
好的 多谢，我打算用kbone 是否可以支持下 哈哈

**Comment by buuing** [comment]
最多过几天兼容一下原生的`微信小程序组件`, 我想把精力主要放在`原生js`和`canvas`上面

**Comment by zdwork** [comment]
兼容原生 微信小程序组件 ，那就厉害了 ，我全网找这个转盘就你这个效果最好

**Comment by buuing** [comment]
谢谢夸奖, 源码基于`lucky-canvas`有兴趣可以一起维护

**Comment by zdwork** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LuckDraw/uni-luck-draw"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 下午4:17
收件人:&nbsp;"LuckDraw/uni-luck-draw"<uni-luck-draw@noreply.github.com&gt;;
抄送:&nbsp;"政达"<987978655@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LuckDraw/uni-luck-draw] 请问怎么分别设置转盘的启动速度和停止速度 (#5)



方便加个微信不 哈哈


 
最多过几天兼容一下原生的微信小程序组件, 我想把精力主要放在原生js和canvas上面

**Comment by zdwork** [comment]
方便加个微信不 哈哈

**Comment by buuing** [comment]
`new_ldq`
