### ISSUE TITLE
请问是否可以支持奖品名称和奖品图片分别布局？是否可以初始化时候指针不指向具体奖品

### ISSUE THREAD

**Issue by menglyf** [LuckDraw/uni-luck-draw#7]
如图

1. 奖品名称和奖品图片分开布局
2. 指针不指向具体奖品

![image](https://user-images.githubusercontent.com/26423790/102734187-2e7dce80-437a-11eb-80ba-bccca80e5e48.png)

**Comment by buuing** [comment]
都可以，请你仔细阅读文档谢谢！

**Comment by menglyf** [comment]
> 都可以，请你仔细阅读文档谢谢！

第二个问题确实是我个人使用不规范，已经实现
第一个问题目前我能实现到下图样式：
![image](https://user-images.githubusercontent.com/26423790/102745456-f8027c80-4396-11eb-88b2-964f5d86ef9e.png)
途中黄色标注需要连接，请问可以实现吗

**Comment by buuing** [comment]
1, 文字目前不能加弧度, 后期会考虑实现
2, 边框不能加线, 因为边框不参与旋转!

你这个效果的话, 可以尝试让ui把单独的扇形切出来, 然后每个奖品你只放一张扇形图片

**Comment by menglyf** [comment]
> 1, 文字目前不能加弧度, 后期会考虑实现
> 2, 边框不能加线, 因为边框不参与旋转!
> 
> 你这个效果的话, 可以尝试让ui把单独的扇形切出来, 然后每个奖品你只放一张扇形图片

请问stop方法是否可以支持让指针停在两个扇形中间？有的业务场景接口报错或者是设置了抽奖规则导致抽奖失败，需要停在两个奖品之间

**Comment by buuing** [comment]
> 请问stop方法是否可以支持让指针停在两个扇形中间？有的业务场景接口报错或者是设置了抽奖规则导致抽奖失败，需要停在两个奖品之间

你这个想法很不错, 我会在后面去实现这个功能的, 目前来说, 你可以通过`v-if`重新渲染一次抽奖插件来尝试看看能不能达到你想要的效果

**Comment by menglyf** [comment]
> > 请问stop方法是否可以支持让指针停在两个扇形中间？有的业务场景接口报错或者是设置了抽奖规则导致抽奖失败，需要停在两个奖品之间
> 
> 你这个想法很不错, 我会在后面去实现这个功能的, 目前来说, 你可以通过`v-if`重新渲染一次抽奖插件来尝试看看能不能达到你想要的效果

v-if我没有实现，调用了一下组件的init方法可以实现
```js
this.$refs.LuckyWheel.init()
```

不清楚这样解决会不会引起别的bug

**Comment by buuing** [comment]
**clever! 对于`init`这个方法确实是用于初始化, 那你先试试吧, 不行的话搭配`v-if`应该会更好用**

**Comment by menglyf** [comment]
> **clever! 对于`init`这个方法确实是用于初始化, 那你先试试吧, 不行的话搭配`v-if`应该会更好用**

是可以实现，但是效果不是特别好，比较好的效果是平稳的滚动到两个扇形中间，谢谢作者大大

**Comment by buuing** [comment]
> 是可以实现，但是效果不是特别好，比较好的效果是平稳的滚动到两个扇形中间，谢谢作者大大

没事的, 非常欢迎反馈问题, 我已将你期望列为需求优化, 将会在后续的版本更新去支持

**Comment by buuing** [comment]
最新版已通过npm发布, Hbuilder导入明天更新
- stop方法传入-1时游戏立即停止, 同时指针指向转盘缝隙, 此时end回调不触发
