### ISSUE TITLE
是否可以给奖品添加点击事件，回调函数参数返回索引

### ISSUE THREAD

**Issue by tuohuang** [LuckDraw/uni-luck-draw#9]
是否可以给奖品添加点击事件，回调函数参数返回索引

**Comment by buuing** [comment]
无法添加, 因为 `uni-app` 并未提供 **`canvasContext2D.isPointInPath()` API** , 导致我无法得知你点击了哪个范围 🤣

**Comment by tuohuang** [comment]
谢谢

**Comment by buuing** [comment]
> 谢谢

用着顺手可以点个`star`支持一下
